-- 1. View Raw Customer Data
SELECT * from Customer_Data

-- 2. Gender Distribution Analysis
-- Calculate the total count and percentage distribution of customers by gender.
SELECT Gender, Count(Gender) as TotalCount,
Count(Gender) *100.0 / (Select Count(*) from Customer_Data)  as Percentage
from Customer_Data
Group by Gender

-- 3. Contract Type Distribution
-- Analyze the distribution of customers across different contract types.
SELECT Contract, Count(Contract) as TotalCount,
Count(Contract)  *100.0 / (Select Count(*) from Customer_Data)  as Percentage
from Customer_Data
Group by Contract

-- 4. Revenue Contribution by Customer Status
-- Evaluate total customer count and total revenue generated by each customer status.
-- Also calculates the percentage contribution to total revenue.
SELECT Customer_Status, Count(Customer_Status) as TotalCount, Sum(Total_Revenue) as TotalRev,
Sum(Total_Revenue) / (Select sum(Total_Revenue) from Customer_Data) * 100  as RevPercentage
from Customer_Data
Group by Customer_Status


 -- 5. State-wise Customer Distribution
-- Analyze geographic distribution of customers by state.
-- Results are ordered by percentage in descending order to identify top customer-contributing states.
SELECT State, Count(State) as TotalCount,
Count(State) * 100.0 / (Select Count(*) from Customer_Data)  as Percentage
from Customer_Data
Group by State
Order by Percentage desc

-- 6. Unique Internet Service Types
-- Identify distinct internet service categories available in the dataset.
SELECT Distinct Internet_Type
from Customer_Data